#!/bin/sh
set -e

gh_list_repos () {
    curl -s 'https://api.github.com/orgs/keyboardio/repos?per_page=100' | jq -r '.[].full_name' | sort
}

travis_repo_state () {
    repo="$1"

    curl -s "https://api.travis-ci.org/repos/${repo}" -H "Accept: application/vnd.travis-ci.2+json" | jq -r '.repo.last_build_state'
}

for repo in $(gh_list_repos); do
    repo_ci_state=$(travis_repo_state ${repo})

    if [ ! -z "${repo_ci_state}" ]; then
        echo "${repo}: ${repo_ci_state}"
    fi
done
