#!/usr/bin/perl 

use warnings;
use strict;

my $failed_count = 0;
my $run_count =0;
my $target = shift;

my $pwd = `pwd`;
chomp($pwd);
my @files = `git ls-files`;

for my $dir (@files) {
    chdir($pwd) || die $@;
    chomp $dir;
    next if ( !-d $dir );
    next if ( !-f $dir . "/Makefile" );
    chdir($dir);
    print "$dir($target)...";
    my $has_target = `make -pRrq 2>/dev/null |grep ^travis-test 2>/dev/null`;
    if ($has_target) {
        system("make -s $target >.build-log 2>&1");
        my $result = $? >> 8;

        if ($result == 0) {
            print " ok\n";
        } else {
            my $contents = do { local $/; open my $fh, ".build-log"; <$fh>; };
            $contents =~ s/^/ > /mg;
            print " fail\n";
            print STDERR "\n$contents\n";
        }
        unlink(".build-log");
        $failed_count += $result;
        $run_count++;
    } else {
        print " skip\n";
    }
}

print STDERR "Ran tests:          $run_count\n";
print STDERR "Total failures:     $failed_count\n";
exit($failed_count);
#make -pRrq |grep -q '^travis-test:$'
